/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.CEscritorio;
import javax.swing.JOptionPane;

/**
 * Escritorio del Programa de tipo MDI.
 * Está clase contiene los constructores y métodos de creación de la Vista
 * de Escritorio
 * @author Rafa
 */
public class Escritorio extends javax.swing.JFrame {

    private CEscritorio controladorInicio;

    /**
     * Creates new form Inicio
     */
    public Escritorio() {
        initComponents();

        // Hacemos que cuando se inicie ocupe toda la pantalla
        this.setExtendedState(MAXIMIZED_BOTH);
        // Indicamos el titulo de la aplicación
        this.setTitle("Drive Me - Alquiler de coches");

        // Enlazamos con el controlador
        controladorInicio = new CEscritorio(this);

        // Iniciamos las consultas de la base de datos
        controladorInicio.iniciaConsultas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanelInformacion = new javax.swing.JPanel();
        jLabeltitulo = new javax.swing.JLabel();
        jLabelTituloDNI = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelTituloNombre = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTituloApellidos = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelTituloUsuario = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelTituloAcceso = new javax.swing.JLabel();
        jLabelAcceso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemVehiculos = new javax.swing.JMenuItem();
        jMenuItemExtras = new javax.swing.JMenuItem();
        jMenuReservas = new javax.swing.JMenu();
        jMenuItemResyCon = new javax.swing.JMenuItem();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenuItemUsuariosya = new javax.swing.JMenuItem();
        jMenuInformacion = new javax.swing.JMenu();
        jMenuItemTBasica = new javax.swing.JMenuItem();
        jMenuItemTAmpliada = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(51, 204, 255));

        jPanelInformacion.setOpaque(false);

        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabeltitulo.setText("Conectado al Sistema Como:");

        jLabelTituloDNI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTituloDNI.setText("DNI:");

        jLabelDNI.setText("jLabel6");

        jLabelTituloNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTituloNombre.setText("Nombre:");

        jLabelNombre.setText("jLabel7");

        jLabelTituloApellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTituloApellidos.setText("Apellidos:");

        jLabelApellidos.setText("jLabel8");

        jLabelTituloUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTituloUsuario.setText("Usuario:");

        jLabelUsuario.setText("jLabel9");

        jLabelTituloAcceso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTituloAcceso.setText("Acceso:");

        jLabelAcceso.setText("jLabel10");

        javax.swing.GroupLayout jPanelInformacionLayout = new javax.swing.GroupLayout(jPanelInformacion);
        jPanelInformacion.setLayout(jPanelInformacionLayout);
        jPanelInformacionLayout.setHorizontalGroup(
            jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                                .addComponent(jLabelTituloDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                                .addComponent(jLabelTituloNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                                .addComponent(jLabelTituloApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                                .addComponent(jLabelTituloUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                                .addComponent(jLabelTituloAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelInformacionLayout.setVerticalGroup(
            jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloDNI)
                    .addComponent(jLabelDNI))
                .addGap(26, 26, 26)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloNombre)
                    .addComponent(jLabelNombre))
                .addGap(26, 26, 26)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloApellidos)
                    .addComponent(jLabelApellidos))
                .addGap(26, 26, 26)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloUsuario)
                    .addComponent(jLabelUsuario))
                .addGap(26, 26, 26)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloAcceso)
                    .addComponent(jLabelAcceso))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        escritorio.add(jPanelInformacion);
        jPanelInformacion.setBounds(20, 0, 470, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/logo.png"))); // NOI18N
        escritorio.add(jLabel1);
        jLabel1.setBounds(470, 20, 390, 200);

        jMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/inicio.png"))); // NOI18N
        jMenuInicio.setMnemonic('f');
        jMenuInicio.setText("Inicio");
        menuBar.add(jMenuInicio);

        jMenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/archivo.png"))); // NOI18N
        jMenuArchivo.setMnemonic('e');
        jMenuArchivo.setText("Archivo");

        jMenuItemVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/vehiculos.png"))); // NOI18N
        jMenuItemVehiculos.setMnemonic('t');
        jMenuItemVehiculos.setText("Vehículos");
        jMenuItemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVehiculosActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemVehiculos);

        jMenuItemExtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/extras.png"))); // NOI18N
        jMenuItemExtras.setMnemonic('y');
        jMenuItemExtras.setText("Extras");
        jMenuItemExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExtrasActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemExtras);

        menuBar.add(jMenuArchivo);

        jMenuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/reserva.png"))); // NOI18N
        jMenuReservas.setMnemonic('h');
        jMenuReservas.setText("Reservas");

        jMenuItemResyCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/reservasyconsumos.png"))); // NOI18N
        jMenuItemResyCon.setMnemonic('c');
        jMenuItemResyCon.setText("Reservas");
        jMenuItemResyCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResyConActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuItemResyCon);

        jMenuItemClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/clientes.png"))); // NOI18N
        jMenuItemClientes.setMnemonic('a');
        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuReservas.add(jMenuItemClientes);

        menuBar.add(jMenuReservas);

        jMenuConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/configuracion.png"))); // NOI18N
        jMenuConfiguracion.setText("Configuración");

        jMenuItemUsuariosya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/usuario.png"))); // NOI18N
        jMenuItemUsuariosya.setText("Usuarios y Accesos");
        jMenuItemUsuariosya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosyaActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(jMenuItemUsuariosya);

        menuBar.add(jMenuConfiguracion);

        jMenuInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/info.png"))); // NOI18N
        jMenuInformacion.setText("Información");

        jMenuItemTBasica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/info.png"))); // NOI18N
        jMenuItemTBasica.setText("Tarifa Básica");
        jMenuItemTBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTBasicaActionPerformed(evt);
            }
        });
        jMenuInformacion.add(jMenuItemTBasica);

        jMenuItemTAmpliada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/info.png"))); // NOI18N
        jMenuItemTAmpliada.setText("Tarifa Ampliada");
        jMenuItemTAmpliada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTAmpliadaActionPerformed(evt);
            }
        });
        jMenuInformacion.add(jMenuItemTAmpliada);

        menuBar.add(jMenuInformacion);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/salir2.png"))); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        menuBar.add(jMenuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVehiculosActionPerformed

        JFrameVehiculo veh = new JFrameVehiculo();
        veh.setVisible(true);

    }//GEN-LAST:event_jMenuItemVehiculosActionPerformed

    private void jMenuItemExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExtrasActionPerformed
        
        JFrameExtras ext = new JFrameExtras();
        ext.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemExtrasActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        
        JFrameCliente cli = new JFrameCliente();
        cli.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemUsuariosyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosyaActionPerformed
        
        JFrameTrabajador tra = new JFrameTrabajador();
        tra.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemUsuariosyaActionPerformed

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
       
        System.exit(0);
        
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuItemResyConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResyConActionPerformed
        
        controladorInicio.abreReserva();
        
    }//GEN-LAST:event_jMenuItemResyConActionPerformed

    private void jMenuItemTBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTBasicaActionPerformed
        
       JDTarifaBasica tb = new JDTarifaBasica(Escritorio.this, true);
       tb.setLocationRelativeTo(null);
       tb.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemTBasicaActionPerformed

    private void jMenuItemTAmpliadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTAmpliadaActionPerformed
      
       JDTarifaAmpliada ta = new JDTarifaAmpliada(Escritorio.this, true);
       ta.setLocationRelativeTo(null);
       ta.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemTAmpliadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabelAcceso;
    private static javax.swing.JLabel jLabelApellidos;
    private static javax.swing.JLabel jLabelDNI;
    private static javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTituloAcceso;
    private javax.swing.JLabel jLabelTituloApellidos;
    private javax.swing.JLabel jLabelTituloDNI;
    private javax.swing.JLabel jLabelTituloNombre;
    private javax.swing.JLabel jLabelTituloUsuario;
    private static javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabeltitulo;
    public static javax.swing.JMenu jMenuArchivo;
    public static javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenu jMenuInformacion;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemExtras;
    private javax.swing.JMenuItem jMenuItemResyCon;
    private javax.swing.JMenuItem jMenuItemTAmpliada;
    private javax.swing.JMenuItem jMenuItemTBasica;
    private javax.swing.JMenuItem jMenuItemUsuariosya;
    private javax.swing.JMenuItem jMenuItemVehiculos;
    private javax.swing.JMenu jMenuReservas;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPanel jPanelInformacion;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que muestra una excepción de sql
     */
    public void muestraExcepcionSQL() {
        JOptionPane.showMessageDialog(this, "Error en introducción de datos SQL", "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void setjLabelAcceso(String texto) {
        jLabelAcceso.setText(texto);
    }

    public void setjLabelApellidos(String texto) {
        jLabelApellidos.setText(texto);
    }

    public void setjLabelDNI(String texto) {
        jLabelDNI.setText(texto);
    }

    public void setjLabelNombre(String texto) {
        jLabelNombre.setText(texto);
    }
    
    public void setjLabelUsuario(String texto) {
        jLabelUsuario.setText(texto);
    }
    
    public String getjLabelDNI() {
        return jLabelDNI.getText();
    }

    public String getjLabelNombre() {
        return jLabelNombre.getText();
    }
    
    public String getjLabelApellidos() {
        return jLabelApellidos.getText();
    }
    
    /**
     * Método para abrir una nueva reserva recibiendo los parametros de DNI, nombre y apellidos del trabajador.
     * @param dni
     * @param nombre
     * @param apellidos
     */
    
    public void abreNuevaReserva(String dni, String nombre, String apellidos) {
        JFrameReserva re = new JFrameReserva(dni, nombre, apellidos);
        re.setVisible(true);
    }
    
    
}
