/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.CJDPago;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 * JDialog de Pago del Programa.
 * Está clase contiene los constructores y métodos de creación de la Vista
 * de JDialog de Pago. Este dialog será una ventana que se abre desde el JFrame de Reserva.
 * La función de esta ventana es la de realizar un pago de la reserva seleccionada.
 * @author Rafa
 */
public class JDPago extends javax.swing.JDialog {
    
    private CJDPago controladorPagos;
    private boolean funcion = true;

    /**
     * Creates new form JDPago
     * @param parent
     * @param modal
     */
    public JDPago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorPagos = new CJDPago(this);    
        desactivarCampos();
    }
    
     /**
     * Creates new form JDPago
     * @param idReserva
     * @param parent
     * @param modal
     */
    public JDPago(int idReserva, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controladorPagos = new CJDPago(this);
        
        jTextFieldIdReserva.setText(String.valueOf(idReserva));
        controladorPagos.rellenaTablaExtras();
        ocultarColumnasExtras();
        controladorPagos.rellenaTablaPagosPorId();
        controladorPagos.rellenaCamposPagoNuevo();
        jDateChooserFEmision.setDate(controladorPagos.fechaActual());
        desactivarCampos();
        jButtonEditar.setEnabled(false);
        jButtonEliminar.setEnabled(false);
    }
    
       /**
     * Creates new form JDPago
     * @param idReserva
     * @param ver
     * @param parent
     * @param modal
     */
    public JDPago(int idReserva, boolean ver, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        if (ver==true) {
        controladorPagos = new CJDPago(this);
        
        jTextFieldIdReserva.setText(String.valueOf(idReserva));
        controladorPagos.rellenaTablaExtras();
        ocultarColumnasExtras();
        controladorPagos.rellenaTablaPagosPorId();
        desactivarCampos();
        jPanelOpcionesPago.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelExtras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExtras = new javax.swing.JTable();
        jPanelListaPagos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaPagos = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jPanelOpcionesPago = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNumFactura = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldIdReserva = new javax.swing.JTextField();
        jComboBoxTipoPago = new javax.swing.JComboBox<>();
        jTextFieldIva = new javax.swing.JTextField();
        jTextFieldTotalPago = new javax.swing.JTextField();
        jDateChooserFEmision = new com.toedter.calendar.JDateChooser();
        jDateChooserFPago = new com.toedter.calendar.JDateChooser();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCosteReserva = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelExtras.setBackground(new java.awt.Color(204, 204, 255));
        jPanelExtras.setBorder(javax.swing.BorderFactory.createTitledBorder("Extras Seleccionados"));

        jTableExtras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableExtras);

        javax.swing.GroupLayout jPanelExtrasLayout = new javax.swing.GroupLayout(jPanelExtras);
        jPanelExtras.setLayout(jPanelExtrasLayout);
        jPanelExtrasLayout.setHorizontalGroup(
            jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanelExtrasLayout.setVerticalGroup(
            jPanelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );

        jPanelListaPagos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelListaPagos.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Facturas"));

        jTableListaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableListaPagos);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/nuevo.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/borrar.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaPagosLayout = new javax.swing.GroupLayout(jPanelListaPagos);
        jPanelListaPagos.setLayout(jPanelListaPagosLayout);
        jPanelListaPagosLayout.setHorizontalGroup(
            jPanelListaPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addGroup(jPanelListaPagosLayout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelListaPagosLayout.setVerticalGroup(
            jPanelListaPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaPagosLayout.createSequentialGroup()
                .addGroup(jPanelListaPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanelOpcionesPago.setBackground(new java.awt.Color(0, 255, 204));
        jPanelOpcionesPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de Pago"));

        jLabel1.setText("Numero de Factura:");

        jLabel2.setText("Matricula Vehiculo de Reserva:");

        jLabel3.setText("Tipo de Pago:");

        jLabel4.setText("IVA:");

        jLabel5.setText("Total de Pago:");

        jLabel6.setText("Fecha de Emisión:");

        jLabel7.setText("Fecha de Pago:");

        jComboBoxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Ingreso Bancario" }));

        jTextFieldTotalPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTotalPagoKeyTyped(evt);
            }
        });

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/guardar.gif"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Salir");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Id y Coste de Reserva:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel9.setText("%21");

        javax.swing.GroupLayout jPanelOpcionesPagoLayout = new javax.swing.GroupLayout(jPanelOpcionesPago);
        jPanelOpcionesPago.setLayout(jPanelOpcionesPagoLayout);
        jPanelOpcionesPagoLayout.setHorizontalGroup(
            jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelOpcionesPagoLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserFPago, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserFEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxTipoPago, javax.swing.GroupLayout.Alignment.TRAILING, 0, 152, Short.MAX_VALUE)
                                .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldNumFactura)
                                .addComponent(jTextFieldTotalPago)
                                .addComponent(jTextFieldIva)
                                .addGroup(jPanelOpcionesPagoLayout.createSequentialGroup()
                                    .addComponent(jTextFieldIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldCosteReserva)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcionesPagoLayout.createSequentialGroup()
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelOpcionesPagoLayout.setVerticalGroup(
            jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesPagoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCosteReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserFEmision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserFPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelExtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListaPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanelOpcionesPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcionesPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelListaPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
        if(getTotal().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes introducir un pago total", "Error en Pago", JOptionPane.ERROR_MESSAGE);
            jTextFieldTotalPago.requestFocus();
            return;
        }
        
        if(jDateChooserFEmision.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "Debes introducir una fecha de emisión", "Error en Fecha de Emision", JOptionPane.ERROR_MESSAGE);
            jDateChooserFEmision.requestFocus();
            return;
        }
        
         if(jDateChooserFPago.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "Debes introducir una fecha de pago", "Error en Fecha de Pago", JOptionPane.ERROR_MESSAGE);
            jDateChooserFEmision.requestFocus();
            return;
        }
        
        if (funcion == true) {
            if(controladorPagos.guardaPago() == true) {
               controladorPagos.rellenaTablaPagosPorId();
               jButtonGuardar.setEnabled(false);
               jButtonEditar.setEnabled(true);
            } else {
                 JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar el pago", "Error al guardar", JOptionPane.ERROR_MESSAGE);
            }            
        } else {
            controladorPagos.editaPago();
            controladorPagos.rellenaTablaPagosPorId();
            jButtonGuardar.setEnabled(false);
            jButtonEditar.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

       jPanelOpcionesPago.setVisible(true);
       funcion = false;
       controladorPagos.rellenaCamposPagoEditar();
       jButtonGuardar.setEnabled(true);
                
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       
       this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
       
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "Va a eliminar un Pago ¿Está seguro?",
                "Eliminar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (confirmacion == 0) {
            controladorPagos.borraPago();
        }
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextFieldTotalPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalPagoKeyTyped
     
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
        
    }//GEN-LAST:event_jTextFieldTotalPagoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDPago dialog = new JDPago(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxTipoPago;
    private com.toedter.calendar.JDateChooser jDateChooserFEmision;
    private com.toedter.calendar.JDateChooser jDateChooserFPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelExtras;
    private javax.swing.JPanel jPanelListaPagos;
    private javax.swing.JPanel jPanelOpcionesPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableExtras;
    private javax.swing.JTable jTableListaPagos;
    private javax.swing.JTextField jTextFieldCosteReserva;
    private javax.swing.JTextField jTextFieldIdReserva;
    private javax.swing.JTextField jTextFieldIva;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNumFactura;
    private javax.swing.JTextField jTextFieldTotalPago;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que desactiva los campos de la tabla los cuales no queremos que se modifiquen.
     */
    public void desactivarCampos() {
        jTextFieldNumFactura.setEnabled(false);
        jTextFieldMatricula.setEnabled(false);
        jTextFieldIdReserva.setEnabled(false);
        jTextFieldIva.setEnabled(false);
        jTextFieldCosteReserva.setEnabled(false);
        jDateChooserFEmision.setEnabled(false);
    }
    
    /**
     * ----- GETTERTS
     */
    
    public String getNumFactura(){
        return jTextFieldNumFactura.getText();
    }

    public String getIdReserva(){
        return jTextFieldIdReserva.getText();
    }
    
    public String getTotal(){
        return jTextFieldTotalPago.getText();
    }
    
    public String getTipoPago(){
        String tipo = (String) jComboBoxTipoPago.getSelectedItem();

        return tipo;
    }
    
    /**
     * Método que convierte la fecha de recogida del vehiculo del tipo calendar obtenido en la vista a tipo Date de java
     * @return la fecha en formato java
     */

    public Date getFechaEmision() {
        Calendar cal;
        int d, m, a;
        cal = jDateChooserFEmision.getCalendar();
        if (cal != null) {
            d = cal.get(Calendar.DAY_OF_MONTH);
            m = cal.get(Calendar.MONTH);
            a = cal.get(Calendar.YEAR) - 1900;
        } else {
            d = 01;
            m = 0;
            a = 116;
        }

        return new Date(a, m, d);
    }
    
    /**
     * Método que convierte la fecha de recogida del vehiculo del tipo calendar obtenido en la vista a tipo Date de java
     * @return la fecha en formato java
     */

    public Date getFechaPago() {
        Calendar cal;
        int d, m, a;
        cal = jDateChooserFPago.getCalendar();
        if (cal != null) {
            d = cal.get(Calendar.DAY_OF_MONTH);
            m = cal.get(Calendar.MONTH);
            a = cal.get(Calendar.YEAR) - 1900;
        } else {
            d = 01;
            m = 0;
            a = 116;
        }

        return new Date(a, m, d);
    }
 
    /** ------------------**/
    
    /**
     * -------- SETTERS
     */
    
    public void setCosteReserva(double coste) {
        jTextFieldCosteReserva.setText(String.valueOf(coste));
    }

    public void setIdReserva(int id) {
        jTextFieldIdReserva.setText(String.valueOf(id));
    }

    public void setIva(double iva) {
        jTextFieldIva.setText(String.valueOf(iva));
    }

    public void setMatricula(String matricula) {
        jTextFieldMatricula.setText(matricula);
    }

    public void setNumFactura(int numFactura) {
        jTextFieldNumFactura.setText(String.valueOf(numFactura));
    }

    public void setTotalPago(double total) {
        jTextFieldTotalPago.setText(String.valueOf(total));
    }
    
    public void setTipoPago(String tipoPago) {
        jComboBoxTipoPago.setSelectedItem(tipoPago);
    }
    
    public void setFechaEmision(Date fechaEmision){
        jDateChooserFEmision.setDate(fechaEmision);
    }
    
    public void setFechaPago(Date fechaPago) {
        jDateChooserFPago.setDate(fechaPago);
    }
    
    /**-----------------------**/
    
    /**
     * Tenemos también un método get por si necesitamos que nos devuelva el
     * modelo.
     *
     * @return modelo de la tabla
     */
    public TableModel getTMJTableExtras() {
        return jTableExtras.getModel();
    }

    /**
     * Desde el controlador enviamos el modelo por defecto de la tabla.
     *
     * @param tm
     */
    public void setTMJTableExtras(TableModel tm) {
        jTableExtras.setModel(tm);
    }
    
    /**
     * Tenemos también un método get por si necesitamos que nos devuelva el
     * modelo.
     *
     * @return modelo de la tabla
     */
    public TableModel getTMJTablePagos() {
        return jTableListaPagos.getModel();
    }

    /**
     * Desde el controlador enviamos el modelo por defecto de la tabla.
     *
     * @param tm
     */
    public void setTMJTablePagos(TableModel tm) {
        jTableListaPagos.setModel(tm);
    }
    
    /**
     * Metodo que nos devuelve la fila que hemos seleccionado en la tabla de Pagos. En
     * caso de no seleccionar fila muestra error.
     *
     * @return devuelve la fila seleccionada, menos uno si no se ha seleccionado
     */
    public int getFilaSeleccionadaPagos() {

        if (jTableListaPagos.getSelectedRowCount() > 0) {
            return jTableListaPagos.getSelectedRow();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione al menos una fila", "Error", JOptionPane.ERROR_MESSAGE);
            funcion = true;
            return -1;
        }
    }
    
    /**
     * Tranforma a tipo fecha la fecha que devuelve el tipo jCalendar
     * @return 
     */
    
    /**
     * Método que muestra una excepción de sql
     */
    public void muestraExcepcionSQL() {
        JOptionPane.showMessageDialog(this, "Error en introducción de datos SQL", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
     /**
     * Método que muestra una excepción de sql
     */
    public void muestraExcepcionPagoNulo() {
        JOptionPane.showMessageDialog(this, "No se ha encontrado un pago en dicha fecha de emision", "Error en la busqueda", JOptionPane.ERROR_MESSAGE);
    }
    
    public void excepcionRepetida() {
        JOptionPane.showMessageDialog(this, "El número de factura ya existe", "Error Número Factura", JOptionPane.ERROR_MESSAGE);
    }

     /**
     * Método que oculta la columna de la id de reserva, dni de cliente y dni de trabajador 
     * puesto que el usuario no debe de poder editar dichos campos de nuestro registro.
     */
    public void ocultarColumnasExtras() {
        jTableExtras.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableExtras.getColumnModel().getColumn(0).setMinWidth(0);
        jTableExtras.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
}
