/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.CJDReserva;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 * JDialog de Reserva del Programa.
 * Está clase contiene los constructores y métodos de creación de la Vista
 * de JDialog de Extra. Este dialog será una ventana que se abre desde el JFrame de Reserva.
 * La función de esta ventana es la de introducir o editar reservas.
 * @author Rafa
 */
public class JDReserva extends javax.swing.JDialog {

    private CJDReserva controladorReserva;
    private boolean funcion = false;

    /**
     * Creates new form JDExtra
     *
     * @param parent
     * @param modal
     */
    public JDReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ocultaCampoId();
        desactivarCampos();
        controladorReserva = new CJDReserva(this);
    }

    /**
     * Constructor creado para poder pasar los parametros de Frame inicio del DNI
     * del trabajador que ha iniciado sesion para cuando creamos una nueva reserva
     *
     * @param dniTrabajador
     * @param nombreTrabajador
     * @param apellidosTrabajador
     * @param funcion
     * @param parent
     * @param modal
     */
    public JDReserva(String dniTrabajador, String nombreTrabajador, String apellidosTrabajador, boolean funcion, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ocultaCampoId();
        setFuncion(funcion);
        desactivarCampos();
        jRadioButtonTarifaBasica.setSelected(true);
        controladorReserva = new CJDReserva(this);

        String nombreyapT = nombreTrabajador + " " + apellidosTrabajador;

        jTextFieldDniTrabajador.setText(dniTrabajador);
        jTextFieldNyapTrabajador.setText(nombreyapT);
        // Rellena el jdte chooser de fecha de reserva con la fecha actual del sistema
        jDateChooserFechaReserva.setDate(controladorReserva.fechaActual());

    }

    /**
     * Creamos un constructor para el JDialog que se le puedan pasar los
     * parametros desde el JFrame Reserva. Este sirve para editar los datos.
     * Rellena los campos con los datos de la reserva seleccionada.
     *
     * @param idReserva
     * @param matricula
     * @param modelo
     * @param nyapCliente
     * @param dniCliente
     * @param nyapTrabajador
     * @param idExtra
     * @param nombreExtra
     * @param estado
     * @param tipoTarifa
     * @param fechaReserva
     * @param fechaDevolucion
     * @param dniTrabajador
     * @param costoAlquiler
     * @param fechaRecogida
     * @param parent
     * @param modal
     */
    public JDReserva(int idReserva, String matricula, String modelo, String dniCliente, String nyapCliente, String dniTrabajador, String nyapTrabajador, int idExtra, String nombreExtra, String tipoTarifa, Date fechaReserva, Date fechaRecogida, Date fechaDevolucion, double costoAlquiler, String estado, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ocultaCampoId();
        controladorReserva = new CJDReserva(this);

        jTextFieldId.setText(String.valueOf(idReserva));
        jTextFieldMatricula.setText(matricula);
        jTextFieldModelo.setText(modelo);
        jTextFieldDniCliente.setText(dniCliente);
        jTextFieldNyapCliente.setText(nyapCliente);
        jTextFieldDniTrabajador.setText(dniTrabajador);
        jTextFieldNyapTrabajador.setText(nyapTrabajador);
        jTextFieldIdExtra.setText(String.valueOf(idExtra));
        jTextFieldNombreExtra.setText(nombreExtra);
        jDateChooserFechaReserva.setDate(fechaReserva);
        jDateChooserFechaRecogida.setDate(fechaRecogida);
        jDateChooserFechaDevolucion.setDate(fechaDevolucion);
        jTextFieldCosto.setText(String.valueOf(costoAlquiler));
        jComboBoxEstado.setSelectedItem(estado);

        if (tipoTarifa.equals("Basica")) jRadioButtonTarifaBasica.setSelected(true);
        else jRadioButtonTarifaAmpliada.setSelected(true);
        
        desactivarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldId = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelVehiculo = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldDniCliente = new javax.swing.JTextField();
        jTextFieldNyapCliente = new javax.swing.JTextField();
        jLabelTrabajador = new javax.swing.JLabel();
        jTextFieldDniTrabajador = new javax.swing.JTextField();
        jTextFieldNyapTrabajador = new javax.swing.JTextField();
        jLabelFechaIngreso = new javax.swing.JLabel();
        jDateChooserFechaRecogida = new com.toedter.calendar.JDateChooser();
        jLabelFechaSalida = new javax.swing.JLabel();
        jDateChooserFechaDevolucion = new com.toedter.calendar.JDateChooser();
        jLabelCoste = new javax.swing.JLabel();
        jTextFieldCosto = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonVehiculo = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jLabelExtra = new javax.swing.JLabel();
        jTextFieldNombreExtra = new javax.swing.JTextField();
        jButtonExtra = new javax.swing.JButton();
        jTextFieldIdExtra = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLabelTipoTarifa = new javax.swing.JLabel();
        jRadioButtonTarifaBasica = new javax.swing.JRadioButton();
        jRadioButtonTarifaAmpliada = new javax.swing.JRadioButton();
        jButtonTBasica = new javax.swing.JButton();
        jButtonTAmpliada = new javax.swing.JButton();
        jDateChooserFechaReserva = new com.toedter.calendar.JDateChooser();
        jLabelFechaReserva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("Datos Reservas");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Datos de Reservas"));

        jButtonGuardar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/guardar.gif"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonLimpiar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/borrar.png"))); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCancelar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelVehiculo.setText("Vehiculo:");

        jLabelCliente.setText("Cliente:");

        jLabelTrabajador.setText("Trabajador:");

        jLabelFechaIngreso.setText("Fecha de Recogida:");

        jLabelFechaSalida.setText("Fecha de Devolucion:");

        jLabelCoste.setText("Coste Total:");

        jTextFieldCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostoKeyTyped(evt);
            }
        });

        jLabelEstado.setText("Estado:");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reserva", "En Alquiler", "Pagada", "Anulada" }));

        jButtonVehiculo.setText("...");
        jButtonVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehiculoActionPerformed(evt);
            }
        });

        jButtonCliente.setText("...");
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jLabelExtra.setText("Extra:");

        jButtonExtra.setText("...");
        jButtonExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtraActionPerformed(evt);
            }
        });

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelTipoTarifa.setText("Tipo de Tarifa:");

        jRadioButtonTarifaBasica.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jRadioButtonTarifaBasica);
        jRadioButtonTarifaBasica.setText("Tarifa Básica");

        jRadioButtonTarifaAmpliada.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jRadioButtonTarifaAmpliada);
        jRadioButtonTarifaAmpliada.setText("Tarifa Ampliada");

        jButtonTBasica.setBackground(new java.awt.Color(204, 255, 204));
        jButtonTBasica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/acerca de.png"))); // NOI18N
        jButtonTBasica.setBorder(null);
        jButtonTBasica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTBasica.setRequestFocusEnabled(false);
        jButtonTBasica.setRolloverEnabled(false);
        jButtonTBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTBasicaActionPerformed(evt);
            }
        });

        jButtonTAmpliada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/acerca de.png"))); // NOI18N
        jButtonTAmpliada.setBorder(null);
        jButtonTAmpliada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTAmpliada.setOpaque(false);
        jButtonTAmpliada.setRequestFocusEnabled(false);
        jButtonTAmpliada.setRolloverEnabled(false);
        jButtonTAmpliada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTAmpliadaActionPerformed(evt);
            }
        });

        jLabelFechaReserva.setText("Fecha de Reserva:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTrabajador)
                                    .addComponent(jLabelCliente)
                                    .addComponent(jLabelVehiculo)
                                    .addComponent(jLabelTipoTarifa)
                                    .addComponent(jLabelExtra))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldNombreExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jButtonExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldDniTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldDniCliente)
                                                .addGap(81, 81, 81))
                                            .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCoste)
                                    .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEstado)
                                    .addComponent(jLabelFechaIngreso)
                                    .addComponent(jLabelFechaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCosto)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonCalcular))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButtonTarifaAmpliada)
                                                    .addComponent(jRadioButtonTarifaBasica))
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonTAmpliada, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButtonTBasica, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(jDateChooserFechaRecogida, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(jDateChooserFechaDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooserFechaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonGuardar)
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldNyapCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldNyapTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonLimpiar)
                                .addGap(88, 88, 88)
                                .addComponent(jButtonCancelar)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVehiculo)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVehiculo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jTextFieldDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNyapCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCliente))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrabajador)
                    .addComponent(jTextFieldDniTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNyapTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExtra)
                    .addComponent(jTextFieldNombreExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExtra)
                    .addComponent(jTextFieldIdExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTipoTarifa)
                        .addComponent(jRadioButtonTarifaBasica))
                    .addComponent(jButtonTBasica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonTarifaAmpliada)
                    .addComponent(jButtonTAmpliada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFechaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserFechaReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooserFechaRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserFechaDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcular)
                    .addComponent(jLabelCoste))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {

        if (getMatricula().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes introducir una Matricula", "Error matricula", JOptionPane.ERROR_MESSAGE);
            jTextFieldMatricula.requestFocus();
            return;
        }

        if (getDniCliente().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes introducir un dni del cliente", "Error dni de Cliente", JOptionPane.ERROR_MESSAGE);
            jTextFieldDniCliente.requestFocus();
            return;
        }
        
        if (getNombreExtra().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes introducir un extra", "Error Extra", JOptionPane.ERROR_MESSAGE);
            jTextFieldDniCliente.requestFocus();
            return;
        }
        
        if (jDateChooserFechaRecogida.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "Debes introducir una fecha de recogida", "Error en Fecha de Recogida", JOptionPane.ERROR_MESSAGE);
            jDateChooserFechaRecogida.requestFocus();
            return;
        }
        
        if (jDateChooserFechaDevolucion.getCalendar() == null) {
            JOptionPane.showMessageDialog(this, "Debes introducir una fecha de Devolucion", "Error en Fecha de Devolucion", JOptionPane.ERROR_MESSAGE);
            jDateChooserFechaDevolucion.requestFocus();
            return;
        }

        if (getCoste().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes introducir un precio de coste", "Error en Precio", JOptionPane.ERROR_MESSAGE);
            jTextFieldCosto.requestFocus();
            return;
        }

        if (controladorReserva.guardar() == true) {
            this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }

    }

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldId.setText("");
        jTextFieldMatricula.setText("");
        jTextFieldModelo.setText("");
        jTextFieldDniCliente.setText("");
        jTextFieldNyapCliente.setText("");
        jDateChooserFechaRecogida.setDateFormatString("");
        jDateChooserFechaDevolucion.setDateFormatString("");
        jTextFieldCosto.setText("");
        jComboBoxEstado.setSelectedItem("");

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehiculoActionPerformed

        JDListaVehiculos vv = new JDListaVehiculos(JDReserva.this, true);

        vv.addWindowListener(new WindowAdapter() {
            @Override
            //llamamos al metodo windowClosed que hará algo cuando la ventana que escuchamos se cierre, en este caso el JDialog
            public void windowClosed(WindowEvent evt) {
                // El metodo rellenatabla actualizará la tabla
                controladorReserva.rellenaCamposVehiculo();
            }
        });

        vv.setVisible(true);

    }//GEN-LAST:event_jButtonVehiculoActionPerformed

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed

        JDListaClientes vc = new JDListaClientes(JDReserva.this, true);

        vc.addWindowListener(new WindowAdapter() {
            @Override
            //llamamos al metodo windowClosed que hará algo cuando la ventana que escuchamos se cierre, en este caso el JDialog
            public void windowClosed(WindowEvent evt) {
                // El metodo rellenatabla actualizará la tabla
                controladorReserva.rellenaCamposCliente();
            }
        });

        vc.setVisible(true);

    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jTextFieldCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostoKeyTyped

        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }

    }//GEN-LAST:event_jTextFieldCostoKeyTyped

    private void jButtonExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtraActionPerformed

        JDListaExtras ve = new JDListaExtras(JDReserva.this, true);

        ve.addWindowListener(new WindowAdapter() {
            @Override
            //llamamos al metodo windowClosed que hará algo cuando la ventana que escuchamos se cierre, en este caso el JDialog
            public void windowClosed(WindowEvent evt) {
                // El metodo rellenatabla actualizará la tabla
                controladorReserva.rellenaCamposExtras();
            }
        });

        ve.setVisible(true);

    }//GEN-LAST:event_jButtonExtraActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
    
        if ( controladorReserva.calculaPrecio() == false) {
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un Extra y un Vehiculo");
        }
        
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonTBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTBasicaActionPerformed
        
       JDTarifaBasica tb = new JDTarifaBasica(JDReserva.this, true);
       tb.setLocationRelativeTo(null);
       tb.setVisible(true);
        
    }//GEN-LAST:event_jButtonTBasicaActionPerformed

    private void jButtonTAmpliadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTAmpliadaActionPerformed
        
       JDTarifaAmpliada ta = new JDTarifaAmpliada(JDReserva.this, true);
       ta.setLocationRelativeTo(null);
       ta.setVisible(true);
        
    }//GEN-LAST:event_jButtonTAmpliadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDReserva dialog = new JDReserva(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonExtra;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonTAmpliada;
    private javax.swing.JButton jButtonTBasica;
    private javax.swing.JButton jButtonVehiculo;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private com.toedter.calendar.JDateChooser jDateChooserFechaDevolucion;
    private com.toedter.calendar.JDateChooser jDateChooserFechaRecogida;
    private com.toedter.calendar.JDateChooser jDateChooserFechaReserva;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCoste;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelExtra;
    private javax.swing.JLabel jLabelFechaIngreso;
    private javax.swing.JLabel jLabelFechaReserva;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelTipoTarifa;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTrabajador;
    private javax.swing.JLabel jLabelVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonTarifaAmpliada;
    private javax.swing.JRadioButton jRadioButtonTarifaBasica;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldDniCliente;
    private javax.swing.JTextField jTextFieldDniTrabajador;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdExtra;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNombreExtra;
    private javax.swing.JTextField jTextFieldNyapCliente;
    private javax.swing.JTextField jTextFieldNyapTrabajador;
    // End of variables declaration//GEN-END:variables

    /**
     ********* GETTERS DE JTEXTFIELDS. Devuelven el texto que hay ingresado dentro de los jTextfields de la vista.
     */
    public String getCoste() {
        return jTextFieldCosto.getText();
    }

    public String getDniCliente() {
        return jTextFieldDniCliente.getText();
    }

    public String getDniTrabajador() {
        return jTextFieldDniTrabajador.getText();
    }

    public String getIdReserva() {
        return jTextFieldId.getText();
    }

    public String getIdExtra() {
        return jTextFieldIdExtra.getText();
    }

    public String getNombreExtra() {
        return jTextFieldNombreExtra.getText();
    }

    public String getMatricula() {
        return jTextFieldMatricula.getText();
    }

    public String getModelo() {
        return jTextFieldModelo.getText();
    }
    
    /**
     * Devuelve el objeto seleccionado del combo box de Estado de la vista
     * @return 
     */

    public String getEstado() {
        String estado = (String) jComboBoxEstado.getSelectedItem();

        return estado;
    }
    
    /**
     * Método que devuelve true si está la tarifa basica seleccionada, false si es la tarifa Ampliada 
     * @return 
     */
    
    public boolean getTarifa() {
        if (jRadioButtonTarifaBasica.isSelected()) return true;
        else return false;
    }
        
    /**
     * Método que convierte la fecha de recogida del vehiculo del tipo calendar obtenido en la vista a tipo Date de java
     * @return la fecha en formato java
     */

    public Date getFechaRecogida() {
        Calendar cal = jDateChooserFechaRecogida.getCalendar();
        int d, m, a;
        if (cal != null) {
            d = cal.get(Calendar.DAY_OF_MONTH);
            m = cal.get(Calendar.MONTH);
            a = cal.get(Calendar.YEAR) - 1900;
        } else {
            d = 01;
            m = 0;
            a = 116;
        }

        return new Date(a, m, d);
    }
    
    /**
     * Obtenemos la fecha de ingreso en milisegundos para trabajar con ella haciendo operaciones numéricas
     * @return 
     */
    public long getFechaRecogidaMil() {
       Calendar cal = jDateChooserFechaRecogida.getCalendar();
       if (cal != null) {
       long fechamil = cal.getTimeInMillis();
       return fechamil;
       } else {
           return 1;
       }      
    }

    
    /**
     * Método que convierte la fecha de devolucion del vehiculo del tipo calendar obtenido en la vista a tipo Date de java
     * @return la fecha en formato java
     */
    public Date getFechaDevolucion() {
        Calendar cal =jDateChooserFechaDevolucion.getCalendar();
        int d, m, a;
        if (cal != null) {
            d = cal.get(Calendar.DAY_OF_MONTH);
            m = cal.get(Calendar.MONTH);
            a = cal.get(Calendar.YEAR) - 1900;
        } else {
            d = 01;
            m = 0;
            a = 116;
        }

        return new Date(a, m, d);
    }
    
    /**
     * Obtenemos la fecha de ingreso en milisegundos para trabajar con ella haciendo operaciones numéricas
     * @return 
     */
    
    public long getFechaDevolucionMil() {
       Calendar cal = jDateChooserFechaDevolucion.getCalendar();
       if (cal != null) {
       long fechamil = cal.getTimeInMillis();
       return fechamil;
       } else {
           return 1;
       } 
    }
    
    /**
     **************** FIN DE GETTERS *
     */

    /**
     ****** SETTERS DE JTEXTFIELDS. Introducen código obtenido desde el controlador en los texfields de la vista
     *
     */
    
    public void setMatricula(String matricula) {
        jTextFieldMatricula.setText(matricula);
    }

    public void setModelo(String modelo) {
        jTextFieldModelo.setText(modelo);
    }

    public void setDniCliente(String dni) {
        jTextFieldDniCliente.setText(dni);
    }

    public void setNyapCliente(String nyap) {
        jTextFieldNyapCliente.setText(nyap);
    }

    public void setIdExtra(int idExtra) {
        jTextFieldIdExtra.setText(String.valueOf(idExtra));
    }

    public void setNombreExtra(String nombreExtra) {
        jTextFieldNombreExtra.setText(nombreExtra);
    }
    
    public void setCosteTotal(double coste) {
        jTextFieldCosto.setText(String.valueOf(coste));
    }
    
    
    /***
     * **************** FIN DE LOS SETTERS
     */
    
    
    /**
     * Método que devuelve true o false según se haya puesto la variable a true
     * o false Sirve para enviar al controlador
     *
     * @return
     */
    public boolean getFuncion() {
        return funcion;
    }

    public void setFuncion(boolean funcion) {
        this.funcion = funcion;
    }

    /**
     * Método que muestra una excepción de sql
     */
    public void muestraExcepcionSQL() {
        JOptionPane.showMessageDialog(this, "Error en introducción de datos SQL", "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Método que oculta el campo ID de nuestro interfaz gráfico
     */
    public void ocultaCampoId() {
        jTextFieldId.setVisible(false);
        jTextFieldIdExtra.setVisible(false);
    }

    /**
     * Método que desactiva los campos para que no puedan ser modificados por el
     * usuario manualmente
     */
    public void desactivarCampos() {
        jTextFieldMatricula.setEnabled(false);
        jTextFieldModelo.setEnabled(false);
        jTextFieldDniCliente.setEnabled(false);
        jTextFieldNyapCliente.setEnabled(false);
        jTextFieldDniTrabajador.setEnabled(false);
        jTextFieldNyapTrabajador.setEnabled(false);
        jTextFieldNombreExtra.setEnabled(false);
        jDateChooserFechaReserva.setEnabled(false);
    }

}
