/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.Ccliente;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 * JFrame de Cliente del Programa.
 * Está clase contiene los constructores y métodos de creación de la Vista
 * de JFrame de Cliente. Este frame se llama desde el Escritorio del programa.
 * Esta ventana tiene por función mostrar una tabla con la lista de clientes
 * y unos botones para añadirlos, editarlos o borrarlos.
 * @author Rafa
 */
public class JFrameCliente extends javax.swing.JFrame {

    private Ccliente controladorCliente;

    /**
     * Creates new form JFrameExtras
     */
    public JFrameCliente() {
        initComponents();

        // Declaramos el degault operation para que al cerrar la ventana no salga de la aplicación
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        controladorCliente = new Ccliente(this);

        controladorCliente.rellenaTablaClientes();
        jLabelTotalRegistros.setText("Total Registros " + controladorCliente.getTotalregistros());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExtras = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaClientes = new javax.swing.JTable();
        jLabelTotalRegistros = new javax.swing.JLabel();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jMenuExtras = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuINuevo = new javax.swing.JMenuItem();
        jMenuISalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelExtras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelExtras.setText("Cliente");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)), "Listado de Clientes"));

        jTableListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableListaClientes);

        jLabelTotalRegistros.setText("Total de Registros:");

        jLabelBuscar.setText("Buscar:");

        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyPressed(evt);
            }
        });

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/buscar.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/nuevo.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/borrar.png"))); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotalRegistros)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonBuscar)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonEditar)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTotalRegistros)
                .addGap(5, 5, 5))
        );

        jMenuArchivo.setText("Archivo");

        jMenuINuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuINuevo.setText("Nuevo");
        jMenuINuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuINuevoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuINuevo);

        jMenuISalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuISalir.setText("Salir");
        jMenuISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuISalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuISalir);

        jMenuExtras.add(jMenuArchivo);

        setJMenuBar(jMenuExtras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelExtras)
                .addContainerGap(641, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        controladorCliente.setTotalregistros(0);
        controladorCliente.buscarCliente(jTextFieldBuscar.getText());
        jLabelTotalRegistros.setText("Total Registros " + controladorCliente.getTotalregistros());

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        try {
            controladorCliente.editarCliente();
            jLabelTotalRegistros.setText("Total Registros " + controladorCliente.getTotalregistros());
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(rootPane, "No hay datos");
        }

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "Va a eliminar un cliente ¿Está seguro?",
                "Eliminar",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (confirmacion == 0) {
            controladorCliente.borraCliente();
            jLabelTotalRegistros.setText("Total Registros " + controladorCliente.getTotalregistros());
        }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jMenuINuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuINuevoActionPerformed

        // Creamos un nuevo JDialog de tipo Vehiculo
        JDialog dialog = new JDCliente(JFrameCliente.this, true, true);
        // Creamos un WindowListener, que no hará más que escuchar para un posible evento de ventana
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            //llamamos al metodo windowClosed que hará algo cuando la ventana que escuchamos se cierre, en este caso el JDialog
            public void windowClosed(WindowEvent evt) {
                // El metodo rellenatabla actualizará la tabla
                controladorCliente.rellenaTablaClientes();
                jLabelTotalRegistros.setText("Total Registros " + controladorCliente.getTotalregistros());
            }
        });
        // hacemos visible la ventana JDClientes
        dialog.setVisible(true);

    }//GEN-LAST:event_jMenuINuevoActionPerformed

    private void jMenuISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuISalirActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuISalirActionPerformed

    private void jTextFieldBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyPressed

        //metodo para comprobar que la tecla pulsada es intro
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            controladorCliente.setTotalregistros(0);
            controladorCliente.buscarCliente(jTextFieldBuscar.getText());
            jLabelTotalRegistros.setText("Total Registros " + controladorCliente.getTotalregistros());
        }

    }//GEN-LAST:event_jTextFieldBuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelExtras;
    private javax.swing.JLabel jLabelTotalRegistros;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuExtras;
    private javax.swing.JMenuItem jMenuINuevo;
    private javax.swing.JMenuItem jMenuISalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaClientes;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables

    /**
     * Tenemos también un método get por si necesitamos que nos devuelva el
     * modelo.
     *
     * @return modelo de la tabla
     */
    public TableModel getTMJTableClientes() {
        return jTableListaClientes.getModel();
    }

    /**
     * Desde el controlador enviamos el modelo por defecto de la tabla.
     *
     * @param tm
     */
    public void setTMJTableClientes(TableModel tm) {
        jTableListaClientes.setModel(tm);
    }

    /**
     * Metodo que nos devuelve la fila que hemos seleccionado en la tabla. En
     * caso de no seleccionar fila muestra error.
     *
     * @return devuelve la fila seleccionada, menos uno si no se ha seleccionado
     */
    public int getFilaSeleccionada() {

        if (jTableListaClientes.getSelectedRowCount() > 0) {
            return jTableListaClientes.getSelectedRow();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione al menos una fila", "Error", JOptionPane.ERROR_MESSAGE);
            return -1;
        }
    }

    /**
     * Este método recoge los datos extraidos de la tabla en el controlador y
     * los envia hacia un JDialog nuevo. Además añade un listener para que
     * cuando se cierre la ventana segun hayamos programado repintará la tabla
     *
     * @param dni
     * @param nombre
     * @param apellidos
     * @param direccion
     * @param email
     * @param telefono
     *
     */
    public void AbreEditarCliente(String dni, String nombre, String apellidos, String direccion, int telefono, String email) {
        // Creamos un nuevo JDialog de tipo extra
        JDialog dialog = new JDCliente(dni, nombre, apellidos, direccion, telefono, email, JFrameCliente.this, true);
        // Creamos un WindowListener, que no hará más que escuchar para un posible evento de ventana
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            //llamamos al metodo windowClosed que hará algo cuando la ventana que escuchamos se cierre, en este caso el JDialog
            public void windowClosed(WindowEvent evt) {
                // El metodo rellenatabla actualizará la tabla
                controladorCliente.rellenaTablaClientes();
            }
        });
        // hacemos visible la ventana JDClientes
        dialog.setVisible(true);
    }

    /**
     * Método que muestra una excepción de sql
     */
    public void muestraExcepcionSQL() {
        JOptionPane.showMessageDialog(this, "Error en introducción de datos SQL", "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Método que muestra una excepción de sql
     */
    public void muestraExcepcionClienteNulo() {
        JOptionPane.showMessageDialog(this, "No se ha encontrado el cliente con ese DNI", "Error en cliente", JOptionPane.ERROR_MESSAGE);
    }

}
